<?php

namespace ContainerIRZ7TkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramControllerinputService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oJGdTjn.App\Controller\TelegramController::input()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oJGdTjn.App\\Controller\\TelegramController::input()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'update' => ['privates', 'App\\Dto\\Telegram\\TelegramUpdateDto', NULL, 'Cannot autowire service "App\\Dto\\Telegram\\TelegramUpdateDto": argument "$updateId" of method "__construct()" is type-hinted "int", you should configure its value explicitly.'],
        ], [
            'update' => 'App\\Dto\\Telegram\\TelegramUpdateDto',
        ]))->withContext('App\\Controller\\TelegramController::input()', $container);
    }
}
