<?php

namespace ContainerNtxxw5s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramUpdateDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Telegram\TelegramUpdateDto' shared autowired service.
     *
     * @return \App\Dto\Telegram\TelegramUpdateDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Dto\\Telegram\\TelegramUpdateDto": argument "$updateId" of method "__construct()" is type-hinted "int", you should configure its value explicitly.');
    }
}
