<?php

namespace ContainerUM0dhmD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramInputControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\TelegramInputController' shared autowired service.
     *
     * @return \App\Controller\TelegramInputController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\TelegramInputController'] = $instance = new \App\Controller\TelegramInputController(($container->privates['logger'] ?? self::getLoggerService($container)), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('TELEGRAM_API'));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\TelegramInputController', $container));

        return $instance;
    }
}
