<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDmnwv1f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDmnwv1f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDmnwv1f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDmnwv1f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDmnwv1f\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dmnwv1f',
    'container.build_id' => 'aee2e819',
    'container.build_time' => 1765249752,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDmnwv1f');
