<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR6FpogM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR6FpogM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR6FpogM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR6FpogM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR6FpogM\App_KernelDevDebugContainer([
    'container.build_hash' => 'R6FpogM',
    'container.build_id' => '944ea03a',
    'container.build_time' => 1764205256,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR6FpogM');
