<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUM0dhmD\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUM0dhmD/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerUM0dhmD.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerUM0dhmD\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerUM0dhmD\App_KernelDevContainer([
    'container.build_hash' => 'UM0dhmD',
    'container.build_id' => '1ab03d33',
    'container.build_time' => 1765249740,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUM0dhmD');
