<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmYLwEE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmYLwEE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHmYLwEE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHmYLwEE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHmYLwEE\App_KernelDevDebugContainer([
    'container.build_hash' => 'HmYLwEE',
    'container.build_id' => 'ac727f9b',
    'container.build_time' => 1765416084,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmYLwEE');
